### ISSUE TITLE
Update to DeepSpeech v0.2.0

### ISSUE THREAD

**Issue by lissyx** [RustAudio/deepspeech-rs#2]
Hello,

We are on the verge of getting closer to v0.2.0. So far, current codebase seems to work properly with v0.2.0-alpha5. We don't have any breaking change waiting, but we have a few improvements including loading the model as mmap() and re-worked trie for the language model. I don't think those should be an issue :)

**Comment by lissyx** [comment]
The two changes touching the header are:
 - ade66b015ded24bbefee9c09bb131e578e055492 where we change the visibility
 - 6c4d4f1e68a2a9d9f3119bd0402d6f9a151fc87f where we expose a `print_version`

**Comment by est31** [comment]
Thanks for the note. Will update as soon as there is a release. Looking forward to the awesome improvements of 0.2.0!

**Comment by est31** [comment]
4063d60e90c73a67c0bc17e5fa6793589cf6bc77 has updated this crate to the latest DeepSpeech alpha version. I'll assume this is fixed. Reopening if there are breaking changes in newer alpha releases.
