### ISSUE TITLE
0.6.1 ?

### ISSUE THREAD

**Issue by lissyx** [RustAudio/deepspeech-rs#23]
I see you did update `sys/deepspeech` dep to 0.6.1, wouldn't a new release be indicated ? There are bug-fixes in the library itself, so I guess it's of value for people.

**Comment by est31** [comment]
I don't see [any relevant changes in the API](https://github.com/mozilla/DeepSpeech/compare/v0.6.0..v0.6.1#diff-0317a0e76ece10e0dba742af310a2362). You can just compile the 0.6.1 library with deepspeech-sys 0.6.0. A new release would be a good idea to get #22 out though.

**Comment by lissyx** [comment]
> I don't see [any relevant changes in the API](https://github.com/mozilla/DeepSpeech/compare/v0.6.0..v0.6.1#diff-0317a0e76ece10e0dba742af310a2362). You can just compile the 0.6.1 library with deepspeech-sys 0.6.0. A new release would be a good idea to get #22 out though.

With the current one, we still see references to 0.6.0 model that is kinda buggy. Also, does someone installing current 0.6.0 deepspeech-rs gets libdeepspeech.so 0.6.1?

**Comment by est31** [comment]
>  does someone installing current 0.6.0 deepspeech-rs gets libdeepspeech.so 0.6.1?

You have to download the .so file yourself. deepspeech-rs does not compile the native client for you (yet), see #3. So you are in full control over which version to use.

**Comment by lissyx** [comment]
> > does someone installing current 0.6.0 deepspeech-rs gets libdeepspeech.so 0.6.1?
> 
> You have to download the .so file yourself. deepspeech-rs does not compile the native client for you (yet), see #3. So you are in full control over which version to use.

Yes, that's why having references to 0.6.0 instead of 0.6.1 on crates.io can be misleading 😊

**Comment by est31** [comment]
I've uploaded version 0.6.1 now: https://github.com/RustAudio/deepspeech-rs/releases/tag/v0.6.1

**Comment by lissyx** [comment]
Thanks!
