### ISSUE TITLE
README is misleading

### ISSUE THREAD

**Issue by Jake-Shadle** [RustAudio/deepspeech-rs#26]
The README states that version `0.6.1` of deepspeech is supported, and the link to get the native_client links directly to the 0.6.1 release, but the current published version/repository now use 0.7.1-alphas of deepspeech. This led me down a rabbit hole of compiling tensorflow and deepspeech from source trying to figure out why running the client example was resulting in segfaults.

It turns out the `DS_CreateModel` signature was changed to remove the beamWidth parameter, which resulted in Model always being null (which isn't checked btw). Changing the signature back to the one that matches 0.6.1 makes the example function again correctly.

The best long term solution for this would be #3 as then there should not be a mismatch between the rust bindings and the deepspeech library, but until then, noting that the version of the deepspeech client (usually/always?) matches the crate version would allow people to download/build the correct native shared objects to link with.

Sorry if this is a bit ranty, but this was quite frustrating. :frowning_face:

**Comment by est31** [comment]
Sorry for having caused you confusion! I should have updated it to 0.7.0 when releasing deepspeech-rs 0.7.0, but I forgot to do it. I'll update README to point out that we support 0.7.0. The deepspeech submodule is on 0.7.1-alpha already but nothing has changed in the API yet about it. Again, sorry.

**Comment by Jake-Shadle** [comment]
No worries, thanks for the quick fix!
