### ISSUE TITLE
Change LM parameters

### ISSUE THREAD

**Issue by lissyx** [RustAudio/deepspeech-rs#4]
To be in sync with upstream: https://github.com/mozilla/DeepSpeech/commit/fa7cb1a983c031042ca2da73cb782deb2d0aad6b

**Comment by est31** [comment]
Oh that's very interesting. Maybe this is the reason why the results were so bad. Looking forward to fixing this.

**Comment by lissyx** [comment]
It might, we will release a new 0.4.1 soon as well to fix some mistake on the model

**Comment by est31** [comment]
@lissyx in that file, [BEAM_WIDTH is set to 1024](https://github.com/mozilla/DeepSpeech/blob/fa7cb1a983c031042ca2da73cb782deb2d0aad6b/examples/ffmpeg_vad_streaming/index.js#L11). But in many other files, it's still set to 500 ([example](https://github.com/mozilla/DeepSpeech/blob/1a1608862d93572ae71ed00ce53c333e4cf6d648/examples/vad_transcriber/wavTranscriber.py#L21)). Which one is the correct one?

**Comment by lissyx** [comment]
> @lissyx in that file, [BEAM_WIDTH is set to 1024](https://github.com/mozilla/DeepSpeech/blob/fa7cb1a983c031042ca2da73cb782deb2d0aad6b/examples/ffmpeg_vad_streaming/index.js#L11). But in many other files, it's still set to 500 ([example](https://github.com/mozilla/DeepSpeech/blob/1a1608862d93572ae71ed00ce53c333e4cf6d648/examples/vad_transcriber/wavTranscriber.py#L21)). Which one is the correct one?

Good catch, the example should be fixed to use 500 as well
