### ISSUE TITLE
Update with new API

### ISSUE THREAD

**Issue by lissyx** [RustAudio/deepspeech-rs#5]
We recently merged a PR that exposes new information, via new API calls: https://github.com/mozilla/DeepSpeech/commit/a009361e470b591f20562214122944d9811592ba#diff-0317a0e76ece10e0dba742af310a2362

This allows access to timing information. We have not yet updated our own bindings by exposing this, I can likely try and take care of that here as well.

**Comment by est31** [comment]
> I can likely try and take care of that here as well.

That would be very welcome!

**Comment by paulirotta** [comment]
Currently the lib support deepspeech 4.0 models only, but 4.1 pretrained are available and 5.0 is in alpha.

**Comment by lissyx** [comment]
> Currently the lib support deepspeech 4.0 models only, but 4.1 pretrained are available and 5.0 is in alpha.

No, current cas use `0.4.1` models. Previous `0.4.0` contained a mistake making the model erroneous.
We are working on `0.5.0` as we speak, so I don't see the point of that comment.

**Comment by paulirotta** [comment]
Thanks! I use 0.2.0 release and was getting an an error that the version number in the model does not not match when using an 0.4.1 model. 

I'll switch to master and try prebuilt 0.4.1, hopefully tomorrow. Note that comments in master at https://github.com/RustAudio/deepspeech-rs/commit/140d6b5c25f299c2f68a9e5673096293c378f8b0 still speak about 0.4.0 which may no longer be accurate.

**Comment by lissyx** [comment]
It's still accurate, we keep compatibility between dot releases. And 0.4.0 was made with a mistake hence 0.4.1. However ever yes 0.2.0 are not compatible because the graph is different.

**Comment by paulirotta** [comment]
Confirmed, and thanks. I have deepspeech 0.4.1 working by changing the dependency to

deepspeech = {git = "https://github.com/RustAudio/deepspeech-rs.git", branch = "master"}

**Comment by est31** [comment]
Fixed by  #6
