### ISSUE TITLE
Update to deepspeech 0.5

### ISSUE THREAD

**Issue by est31** [RustAudio/deepspeech-rs#7]
https://github.com/mozilla/DeepSpeech/releases/tag/v0.5.0

**Comment by BlinkyStitt** [comment]
"Added output of word timings" looks like it could be useful for my current project. How much work is it to update to 0.5?

**Comment by est31** [comment]
Not much. I just was busy the last few days and tbh forgot about it. Will update it right away after eating.

**Comment by est31** [comment]
Fixed by the 0.4.0 release: https://github.com/RustAudio/deepspeech-rs/releases/tag/v0.4.0
