### ISSUE TITLE
Update to 0.5.1

### ISSUE THREAD

**Issue by lissyx** [RustAudio/deepspeech-rs#9]
We had to perform a 0.5.1 to fix big issues :)

**Comment by est31** [comment]
@lissyx I've seen the release announcement, from what I saw nothing changed about the cpp library, right? Only the model and maybe the cpp binary changed, no?

**Comment by lissyx** [comment]
Only the library, so since you link to our tree you might want to update that, no ?

**Comment by est31** [comment]
Hmm yeah https://github.com/mozilla/DeepSpeech/pull/2184 would make sense. Although nothing in the header has changed. The library is downloaded by users.

**Comment by lissyx** [comment]
Right, well, it's up to you. Referring to proper commit might still be handy, to ensure people knows it's actually 0.5.1 they need, so we don't get reports of "OH NO YOUR RUST VERSION IS xxx" :)

**Comment by est31** [comment]
Yup, README should definitely be updated.
